"""Change timestamp to string

Revision ID: 11dcfbe8b2da
Revises: 36b7eb5f11db
Create Date: 2024-11-23 00:58:13.055337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11dcfbe8b2da'
down_revision: Union[str, None] = '36b7eb5f11db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'timestamp',
                    existing_type=sa.String(),
                    type_=sa.DateTime(),
                    existing_nullable=False)
    # ### end Alembic commands ###
